#!/bin/bash

USERNAME="myuser"
PASS="myuser"
TOKEN="bc0ee8fffd393bff90e64c709649c2cdc44b56c5"

# login
curl --location --request POST 'localhost:8000/core/authtoken/' \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa' \
--form "username=$USERNAME" \
--form "password=$PASS"

# create
curl --location --request POST 'localhost:8000/core/bookmarks/' \
--header "Authorization: Token $TOKEN" \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa' \
--data-raw '{
    "title": "twitter.com",
    "url": "https://www.twitter.com",
    "user": 1,
    "public": false
}'


# list
curl --location --request GET 'localhost:8000/core/bookmarks/' \
--header "Authorization: Token $TOKEN" \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa'

# retrieve
# you can also query a user's public bookmarks py using the query_param user_id
curl --location --request GET 'localhost:8000/core/bookmarks/1?user_id=1' \
--header "Authorization: Token $TOKEN" \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa'


# delete
curl --location --request DELETE 'localhost:8000/core/bookmarks/1/' \
--header "Authorization: Token $TOKEN" \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa'

# partial update
curl --location --request PATCH 'localhost:8000/core/bookmarks/1/' \
--header "Authorization: Token $TOKEN" \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa' \
--data-raw '{
    "url": "https://www.wikipedia.com"
}'

# update
curl --location --request PUT 'localhost:8000/core/bookmarks/1/' \
--header "Authorization: Token $TOKEN" \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=40ldcryCJPtImDsrGNRAwiOeNmWOpMJj9ZtVwRCBTlZa3hwS26XMNQdaZsnDcELa' \
--data-raw '{
    "title": "facebook",
    "url": "https://www.facebook.com",
    "user": 1
}'
